# Generated by Django 3.2.4 on 2021-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='default_parameters',
            field=models.JSONField(default=dict),
        ),
    ]
