# Generated by Django 3.2.6 on 2021-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_inspector', '0002_query_default_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='default_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
