# Generated by Django 3.2.4 on 2021-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_inspector', '0003_alter_query_default_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='stock',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
