# Generated by Django 3.2.6 on 2021-09-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_inspector', '0004_query_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ('-stock', 'slug'), 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
