# Generated by Django 4.1.11 on 2023-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("query_inspector", "0005_alter_query_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="from_materialized_view",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="query",
            name="from_view",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
