# Generated by Django 4.1.11 on 2024-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("query_inspector", "0006_query_from_materialized_view_query_from_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="slug",
            field=models.SlugField(),
        ),
    ]
